name: covidtracker
description: Keep track of COVID-19 cases world wide

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: 0.12.0+4
  shared_preferences: 0.5.6+3
  auto_animated: any
  url_launcher: 5.4.2
  webview_flutter: 0.3.20
  flutter_webview_plugin: 0.3.11
  fl_chart: 0.9.3
  flutter_launcher_icons: 0.7.4
  ez_localization: ^0.2.2
  ezanimation: 0.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/imgs/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/imgs/
    - lib/lang/
